name: DailyApp
description: "Eine App für den Täglichen gebrauch"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_slidable: ^4.0.1
  intl: ^0.20.2
  mysql_client: ^0.0.27
  shared_preferences: ^2.2.3
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.21.0
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/android/play_store_512.png"
  adaptive_icon_background: "assets/icon/android/res/mipmap-xxxhdpi/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icon/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icon/android/res/mipmap-xxxhdpi/ic_launcher_monochrome.png"
  adaptive_icon_foreground_inset: 8
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true