name: DailyApp
description: "Eine App für den Täglichen gebrauch"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_slidable: ^4.0.1
  intl: ^0.20.2
  mysql_client: ^0.0.27
  shared_preferences: ^2.2.3
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.21.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true