name: DailyApp
description: "Ein App für den Täglichen gebrauch"
publish_to: 'none'
version: 1.1.2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_slidable: ^3.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
